"use server";

import { revalidatePath } from "next/cache";

import { OK, toActionError, type ActionState } from "@/app/actions/shared";
import { getDataContext } from "@/lib/data";
import { getProviders } from "@/lib/providers/registry";
import { ProviderNotConfiguredError } from "@/lib/providers/types";
import type { AIAnalysisRequest } from "@/lib/providers/types";
import { scoreOpportunity } from "@/lib/scoring/engine";
import { summarizeSerp } from "@/lib/scoring/serp";

/**
 * Runs an AI analysis for an opportunity.
 *
 * The model only ever receives the objective payload assembled here, and the
 * result is stored alongside that exact payload so a later reader can audit what
 * the model was and was not told.
 */
export async function analyzeOpportunityAction(
  _prev: ActionState,
  formData: FormData,
): Promise<ActionState> {
  const opportunityId = String(formData.get("opportunityId") ?? "");
  if (!opportunityId) return { ok: false, error: "Missing opportunity id." };

  try {
    const { store, settings } = await getDataContext();
    const opportunity = await store.getOpportunity(opportunityId);
    if (!opportunity) return { ok: false, error: "Opportunity not found." };

    const serpResults = await store.listSerpResults(opportunityId);
    const summary = summarizeSerp(serpResults);
    const breakdown = scoreOpportunity(opportunity, {
      weights: settings.weights,
      thresholds: settings.thresholds,
      demandCalibration: settings.demandCalibration,
    });

    const request: AIAnalysisRequest = {
      opportunity: {
        keyword: opportunity.keyword,
        country: opportunity.country,
        language: opportunity.language,
        searchVolume: opportunity.searchVolume,
        keywordDifficulty: opportunity.keywordDifficulty,
        cpc: opportunity.cpc,
        trend: opportunity.trend,
        utilityType: opportunity.utilityType,
        notes: opportunity.notes,
      },
      serpResults: serpResults.map((result) => ({
        position: result.position,
        domain: result.domain,
        pageType: result.pageType,
        domainAuthority: result.domainAuthority,
        isLowAuthority: result.isLowAuthority,
        isNewSite: result.isNewSite,
        assessment: result.assessment,
        title: result.title,
        notes: result.notes,
      })),
      serpSummary: {
        resultCount: summary.resultCount,
        lowAuthorityCount: summary.lowAuthorityCount,
        newSiteCount: summary.newSiteCount,
        utilityCount: summary.utilityCount,
        articleCount: summary.articleCount,
        unknownAuthorityCount: summary.unknownAuthorityCount,
      },
      scoreSummary: {
        total: breakdown.total,
        decision: breakdown.decision,
        completeness: breakdown.completeness,
        missingFactors: breakdown.missingFactors,
      },
    };

    const providers = getProviders(settings.providers);
    const result = await providers.ai.analyze(request);

    await store.createAnalysis({
      opportunityId,
      provider: providers.ai.id,
      model: result.model,
      content: result.content,
      inputSnapshot: request as unknown as Record<string, unknown>,
    });

    await store.appendActivity({
      entityType: "OPPORTUNITY",
      entityId: opportunityId,
      type: "AI_ANALYSIS_GENERATED",
      summary: `AI analysis generated by ${providers.ai.label}. Recommendation: ${result.content.recommendation} (${result.content.confidence} confidence).`,
      detail: { provider: providers.ai.id, model: result.model },
    });
  } catch (error) {
    if (error instanceof ProviderNotConfiguredError) {
      return { ok: false, error: error.message };
    }
    return toActionError(error);
  }

  revalidatePath(`/opportunities/${opportunityId}`);
  return { ...OK, message: "Analysis complete." };
}
